app:
  active-mq:
    host: localhost
    workload-queue: workload.queue
  postgres:
    host: localhost
  jwt:
    key: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA
    algorithm: HS256
    issuer: main-service
cors:
  allowed-urls: http://localhost:8081
  allowed-methods: OPTIONS, HEAD, GET, PUT, POST, DELETE, PATCH
  allowed-headers: Authorization
spring:
  profiles:
    active:
  application:
    name: main-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${app.postgres.host}:5432/spring-rest
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  activemq:
    broker-url: tcp://${app.active-mq.host}:61616
    user: admin
    password: admin
    packages:
      trust-all: false
      trusted: com.nikolabojanic
    queue:
      deadLetterQueue: DLQ
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
