server:
  port: 8081
app:
  broker-host: "activemq-docker"
spring:
  activemq:
    broker-url: tcp://${app.broker-host}:61616
    user: docker
    password: docker
    packages:
      trust-all: false
      trusted: com.nikolabojanic