app:
  active-mq:
    host: activemq-docker
    workload-queue: workload.queue.docker
spring:
  activemq:
    broker-url: tcp://${app.active-mq.host}:61616
    user: admin
    password: admin
    data:
      mongodb:
        host: mongodb
        database: workload-dev